table customers
	lineageTag: 94b161a9-5539-4c5e-9127-d4394c717ff5

	measure 'Total Profit' = ```
			
			SUMX(
			    orderdetails,
			    (orderdetails[priceEach] - RELATED(products[buyPrice])) 
			    * orderdetails[quantityOrdered]
			)
			```
		lineageTag: 7b3b6dbe-380d-418f-badb-52f4b025e1e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Payments' = SUM(payments[amount])
		lineageTag: cdb194cd-3333-4466-9252-10a27832513d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales' =
			
			SUMX(
			    orderdetails,
			    orderdetails[priceEach] * orderdetails[quantityOrdered]
			)
		formatString: 0.00
		lineageTag: f8c32605-1966-4c1e-b991-dab23efe86c9

	column customerNumber
		dataType: int64
		formatString: 0
		lineageTag: 298c58d1-ab06-4521-a69c-e42c9c971e58
		summarizeBy: none
		sourceColumn: customerNumber

		annotation SummarizationSetBy = Automatic

	column customerName
		dataType: string
		lineageTag: 3c690d4e-103d-4ce6-8428-e18e3fb284d7
		summarizeBy: none
		sourceColumn: customerName

		annotation SummarizationSetBy = Automatic

	column contactLastName
		dataType: string
		lineageTag: 84b9c1c4-67d6-4922-b946-94526e145d0b
		summarizeBy: none
		sourceColumn: contactLastName

		annotation SummarizationSetBy = Automatic

	column contactFirstName
		dataType: string
		lineageTag: 20e79c9a-711e-4826-8e65-a4cd200b5af1
		summarizeBy: none
		sourceColumn: contactFirstName

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 55d527e0-dead-4672-a60d-ff70c263f5be
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column addressLine1
		dataType: string
		lineageTag: 30b5fd07-c97c-409e-8943-6340c76bddf6
		summarizeBy: none
		sourceColumn: addressLine1

		annotation SummarizationSetBy = Automatic

	column addressLine2
		dataType: string
		lineageTag: 8b9d630e-dfe1-4015-b4a7-7c964cda0b79
		summarizeBy: none
		sourceColumn: addressLine2

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 9a55cc67-b43c-4dc9-9d67-89c6b99f126b
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: e1d1c4bc-bf56-4d01-ba0c-e391bb4d3741
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column postalCode
		dataType: string
		lineageTag: a05a3e08-bc24-4ce6-9dbd-154c4c3203a6
		summarizeBy: none
		sourceColumn: postalCode

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 05ed79f1-119e-4449-b62b-97fcb21ff32e
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column salesRepEmployeeNumber
		dataType: int64
		formatString: 0
		lineageTag: 141fceaf-c002-4219-9cd5-47a8422d6944
		summarizeBy: none
		sourceColumn: salesRepEmployeeNumber

		annotation SummarizationSetBy = Automatic

	column creditLimit
		dataType: string
		lineageTag: 8c99ebb1-e400-411d-aa3e-fe7635bc1949
		summarizeBy: none
		sourceColumn: creditLimit

		annotation SummarizationSetBy = Automatic

	partition customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\tasks\classic_models_dashboard\data\customers.csv"),[Delimiter=",", Columns=13, Encoding=65001]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customerNumber", Int64.Type}, {"customerName", type text}, {"contactLastName", type text}, {"contactFirstName", type text}, {"phone", type text}, {"addressLine1", type text}, {"addressLine2", type text}, {"city", type text}, {"state", type text}, {"postalCode", type text}, {"country", type text}, {"salesRepEmployeeNumber", Int64.Type}, {"creditLimit", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

