table employees
	lineageTag: 37dcb77a-b68e-4458-83de-43d39cf09383

	column employeeNumber
		dataType: int64
		formatString: 0
		lineageTag: 6057f8a9-d03b-4729-b9c3-0e869156d588
		summarizeBy: none
		sourceColumn: employeeNumber

		annotation SummarizationSetBy = Automatic

	column lastName
		dataType: string
		lineageTag: 074fc47b-32a0-4e77-a5b2-bb5c5affaed4
		summarizeBy: none
		sourceColumn: lastName

		annotation SummarizationSetBy = Automatic

	column firstName
		dataType: string
		lineageTag: aa151197-ae93-4b79-ac36-92e79f725eb0
		summarizeBy: none
		sourceColumn: firstName

		annotation SummarizationSetBy = Automatic

	column extension
		dataType: string
		lineageTag: 81b82a85-20b1-4784-b07f-8dbf2a8b39ee
		summarizeBy: none
		sourceColumn: extension

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: b8ba5435-0b82-4496-a09b-9e59b046ccec
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column officeCode
		dataType: int64
		formatString: 0
		lineageTag: c44c6496-f5e9-4a2f-b097-202269b96452
		summarizeBy: none
		sourceColumn: officeCode

		annotation SummarizationSetBy = Automatic

	column reportsTo
		dataType: int64
		formatString: 0
		lineageTag: 802cc2c8-9303-46ae-b13c-aef44a982772
		summarizeBy: sum
		sourceColumn: reportsTo

		annotation SummarizationSetBy = Automatic

	column jobTitle
		dataType: string
		lineageTag: bc857d7f-97b7-47ff-9aa0-62b21a6c643c
		summarizeBy: none
		sourceColumn: jobTitle

		annotation SummarizationSetBy = Automatic

	partition employees = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\tasks\classic_models_dashboard\data\employees.csv"),[Delimiter=",", Columns=8, Encoding=1256, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"employeeNumber", Int64.Type}, {"lastName", type text}, {"firstName", type text}, {"extension", type text}, {"email", type text}, {"officeCode", Int64.Type}, {"reportsTo", Int64.Type}, {"jobTitle", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

