table offices
	lineageTag: 8f8dcee7-d5e5-4b3f-b7e1-0df90d55cb6a

	column officeCode
		dataType: int64
		formatString: 0
		lineageTag: 05163fea-412d-4849-a15e-d0ed7de427b4
		summarizeBy: none
		sourceColumn: officeCode

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 26cb16cd-227f-4419-a343-85accc5bc4b1
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: deee2c37-334a-4dfe-a6ae-e6074093adcd
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column addressLine1
		dataType: string
		lineageTag: f35ce55c-f304-4075-b757-651586216cbf
		summarizeBy: none
		sourceColumn: addressLine1

		annotation SummarizationSetBy = Automatic

	column addressLine2
		dataType: string
		lineageTag: 2a5847d1-5053-411c-926d-eb4d43b2efdc
		summarizeBy: none
		sourceColumn: addressLine2

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 543cbf98-be60-4b28-a7a4-9bda23d413e7
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 21a5f906-d662-44bf-820a-bd0e564a75f8
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column postalCode
		dataType: string
		lineageTag: fe793ab5-9425-418c-ab82-8b65f708d668
		summarizeBy: none
		sourceColumn: postalCode

		annotation SummarizationSetBy = Automatic

	column territory
		dataType: string
		lineageTag: 470da266-430d-4944-a921-b63b1a084ac8
		summarizeBy: none
		sourceColumn: territory

		annotation SummarizationSetBy = Automatic

	partition offices = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\tasks\classic_models_dashboard\data\offices.csv"),[Delimiter=",", Columns=9, Encoding=1256, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"officeCode", Int64.Type}, {"city", type text}, {"phone", type text}, {"addressLine1", type text}, {"addressLine2", type text}, {"state", type text}, {"country", type text}, {"postalCode", type text}, {"territory", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

