table payments
	lineageTag: 8536366f-609c-48e4-83d7-6c1427282cc9

	column customerNumber
		dataType: int64
		formatString: 0
		lineageTag: 7666d0d0-8b6f-4c3d-9772-b0beaa9ef641
		summarizeBy: none
		sourceColumn: customerNumber

		annotation SummarizationSetBy = Automatic

	column checkNumber
		dataType: string
		lineageTag: 13631c7a-4b8e-4a53-ba52-23d930d98f49
		summarizeBy: none
		sourceColumn: checkNumber

		annotation SummarizationSetBy = Automatic

	column paymentDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: f86173fa-e518-4186-8c43-466151ff0261
		summarizeBy: none
		sourceColumn: paymentDate

		variation Variation
			isDefault
			relationship: 4845d4b7-7194-4aff-bc7f-19fc8362c2a0
			defaultHierarchy: LocalDateTable_099e2de5-c18b-4e44-ab66-7cf083816d96.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column amount
		dataType: double
		formatString: #,0
		lineageTag: 1738ccd5-1a2d-4472-a107-5ce37a59fe54
		summarizeBy: sum
		sourceColumn: amount

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition payments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\tasks\classic_models_dashboard\data\payments.csv"),[Delimiter=",", Columns=4, Encoding=1256, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customerNumber", Int64.Type}, {"checkNumber", type text}, {"paymentDate", type date}, {"amount", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

